### ISSUE TITLE
Combined sources?

### ISSUE THREAD

**Issue by codefrau** [pablomarx/Smalltalk76#5]
For a global text search it would be nice to have an all-in-one HTML file, basically a concatenation of all the separate files.

**Comment by pablomarx** [comment]
@bertfreudenberg I added a file `Smalltalk.Sources.5.5k.html` to the `docs` dir ([live link](http://pablomarx.github.io/Smalltalk76/Smalltalk.Sources.5.5k.html)).  This contains a concatenation of the HTML renders. The indentation won't be correct as restore_alto_tools does some funky JS to emulate it, and the JS was taking minutes on one of my machines due to the overall DOM size.  I'll look into fixing that JS later.

**Comment by pablomarx** [comment]
The JS code from restore_alto_files does:

`var tabs = document.getElementsByClassName("tab");`

Which results in 24,886 elements.  Then it executes a `getBoundingClientRect()` on each.  This is likely why it's very angry.

**Comment by codefrau** [comment]
Nice! Thank you :)

The HTML is a little heavy anyways, yes. A global CSS style definition would cut down the size considerably. 

As for the tab logic, `val` seems to always be `79` so I'm not sure what the fancy calculation is supposed to accomplish ...

**Comment by pablomarx** [comment]
I've created a new branch, issue5-noscript.  This removed the JS code that did tab expansion, replacing it with CSS.   Besides being faster, nested indentation is actually nested now!

Bootstrap before:

![screen shot 2018-09-09 at 9 17 00](https://user-images.githubusercontent.com/179162/45266565-93af8f00-b411-11e8-9e65-881a3e7cf4d9.png)

Bootstrap after:

![screen shot 2018-09-09 at 9 19 52](https://user-images.githubusercontent.com/179162/45266568-9ad69d00-b411-11e8-9e60-728c042e10a5.png)

Smalltalk.Sources.5.5k before:

![screen shot 2018-09-09 at 9 17 58](https://user-images.githubusercontent.com/179162/45266571-a88c2280-b411-11e8-9ab0-499998ea2eff.png)

Smalltalk.Sources.5.5k after:

![screen shot 2018-09-09 at 9 17 47](https://user-images.githubusercontent.com/179162/45266574-afb33080-b411-11e8-925e-9e152ca310a2.png)

**Comment by codefrau** [comment]
Oh, I like the look!!!

**Comment by pablomarx** [comment]
Is there anything else outstanding for this issue?  We have the combined sources HTML file, now with proper indentation.

**Comment by codefrau** [comment]
I think this is done. Outstanding! 👍
