### ISSUE TITLE
Parc Place font

### ISSUE THREAD

**Issue by codefrau** [pablomarx/Smalltalk76#7]
I just found @RebeccaRGB's "Parc Place" font which includes the special St-76 characters in its Private Use area: http://www.kreativekorp.com/software/fonts/urbanrenewal.shtml

Using that font would be an awesome way to typeset the sources.

**Comment by pablomarx** [comment]
I've created a branch `issue7-webfont`.  It presently uses the ParcPlace font only on the combined sources file.  Would you care to take a look and let me know how it looks?  If it looks good I'll get it applied to all the other HTML files.

**Comment by codefrau** [comment]
Looks cool!

Issues: 
1. we need to include the font's license file that came in the zip
2. I didn't realize you could use `TTF` as a web font directly ... is that supported across browsers nowadays? Might still be better to convert to `WOFF`.
3. the ⦂ doesn't look right (e.g. in the **and⦂** definition in your screenshot). Not sure if that's a problem with the font or the conversion

**Comment by pablomarx** [comment]
1. Yes – I will include the license and proper attribution 
2. I haven't a clue – I will research that
3. I believe it's the font, as the HTML file is relatively unchanged – I only replaced style attributes with class attributes and introduced the CSS at the top.  When time permits I'll inspect the font to give a definitive answer (hopefully this weekend).

**Comment by codefrau** [comment]
Some chars need a new substitution, e.g. ⓢ (as seen in the "Compiler Defaults" section) is `U+E013` in that font.

I believe it might work if you just map `00-1F` chars to `E000-E01F` (which is in the Unicode Private Use area) and leave the rest as original ...

**Comment by RebeccaRGB** [comment]
I can make a version of Parc Place that uses your mapping, so you won't
have to change anything. It will just be a few hours until I'm off work.

-- Rebecca Bettencourt

**Comment by pablomarx** [comment]
@RebeccaRGB Awesome thank you! I also don't mind making the change on my end, so maybe we defer to @bertfreudenberg as I believe he wants to read this into his Notetaker VM.  Do you have a preference @bertfreudenberg ? I reckon @RebeccaRGB's change would make your life easier.

**Comment by codefrau** [comment]
Yes, I think keeping our mapping would be good, the advantage being that even when viewed with another font it's still mostly readable.
@RebeccaRGB here's the mapping I have been using (https://github.com/bertfreudenberg/Smalltalk78/blob/master/vm.js#L342)
```
    toUnicode: {
        '\x00': "␀",
        '\x01': "≤",
        '\x02': "␂",
        '\x03': "⦂",
        '\x04': "␄",
        '\x05': "√",
        '\x06': "≡",
        '\x07': "◦",
        '\x08': "␈",
        //'\x09': "␉",    // keep TAB
        '\x0a': "␊",
        '\x0b': "␋",
        '\x0c': "␌",
        '\x0d': "\n",   // CR becomes LF
        '\x0e': "≠",
        '\x0f': "↪",
        '\x10': "␐",
        '\x11': "⇑",
        '\x12': "≥",
        '\x13': "ⓢ",
        '\x14': "◣",
        '\x15': "¬",
        '\x16': "∢",
        '\x17': "⌾",
        '\x18': "▱",
        '\x19': "➲",
        '\x1a': "␚",
        '\x1b': "⇒",
        '\x1c': "␜",
        '\x1d': "◻︎",
        '\x1e': "◢",
        '\x1f': "␟",
        '\x7f': "␡",
        '_'   : "←",
        '^'   : "↑",
    },
```

This is exciting!

**Comment by RebeccaRGB** [comment]
Here it is. "Parc Place" is just an updated version, adding additional Unicode characters. "Parc Place Legacy" is the version using your mapping.
[parcplace-web.zip](https://github.com/pablomarx/Smalltalk76/files/2359643/parcplace-web.zip)

**Comment by codefrau** [comment]
Awesome! @pablomarx you need to switch to Parc Place Legacy so characters like ⓢ show up as intended.

**Comment by pablomarx** [comment]
@bertfreudenberg I've switched to the legacy font in the `issue7-webfont` branch: 

![screen shot 2018-09-09 at 13 11 51](https://user-images.githubusercontent.com/179162/45268480-f44ec400-b431-11e8-8e8b-c392e99a4923.png)

Let me know what you think – I'll merge it into master if you give the thumbs up.

@RebeccaRGB Thank you so much for the changes – it is looking great! I've included your license and URL inside the CSS file, a copy of the license inside the docs dir, and included a mention/link in the docs' README.  Please let me know if there's anything else I should do.

**Comment by codefrau** [comment]
Looks great! The `Parc Place Legacy.ttf` you used works fine.
The `woff` / `woff2` versions appear to be missing the non-standard glyphs like `ⓢ` or `⦂`:
https://jsfiddle.net/cvu3964q/19/
@RebeccaRGB maybe you did not include these glyphs when generating the web fonts?

**Comment by RebeccaRGB** [comment]
Indeed, I selected the wrong setting when converting to woff. Apologies. Try these:
[parcplace-web.zip](https://github.com/pablomarx/Smalltalk76/files/2364659/parcplace-web.zip)
@pablomarx That's more than sufficient. Thank you, it was my pleasure.

**Comment by codefrau** [comment]
I think this is great. The only thing we might do is include the other font formats to "bullet-proof" for older web browsers:
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#font-face_in_more_detail

**Comment by pablomarx** [comment]
@bertfreudenberg I've added all the fonts and the fallback CSS per the MDN link.  Let me know if you think there is anything else that needs to be done for this issue.

**Comment by codefrau** [comment]
I think we're done here. Thanks everyone!
